@startuml
left to right direction
skinparam packageStyle rectangle

actor User

rectangle "Sentinel Password Manager" {
  User --> (Load Vaults)
  User --> (Authenticate Vault)
  User --> (Create Vault)
  User --> (Add Entry)
  User --> (Edit Entry)
  User --> (Delete Entry)
  User --> (Logout Vault)
  User --> (Find Entries By Ascending)
  User --> (Find Entries By Descending)
  User --> (Generate Password)
  User --> (Save Vaults)
}
@enduml
